### PR TITLE
add elasticsearch2.4

### PR DESCRIPTION
**Pull request by ndp**

### CODE REVIEW

**Comment by micahbf** [comment]
Also, not sure what this repo is for, but if it's only for cross-product stuff, elasticsearch is only used in Collect.

**Comment by micahbf** [comment]
@ndp is this still relevant?

**Review by tgaff — COMMENTED** [review]
Adding a review to get the bots off my back.

I also don't know whether we're using this repo any where.  But if we are, then I agree with Micah - I don't think we use Elasticsearch outside of Collect.

It would be nice to get a single docker-compose for connect though - it seems like we have small subtle variations in the compose files between each connect repo.  These have resulted in multiple issues where something was run slightly different in one repo vs. the other.

**Review by micahbf — COMMENTED** [review]
Also reviewing so I stop getting bothered about this.

**Comment by ndp** [comment]
FYI I use this locally so I don't have to install tools... and it holds docker build that don't fit anywhere else.

**Pull request closed without merging**
